version: "1.0"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: adbms
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33069:3306
